# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: https://jiaxun-li.github.io/blogs/en/
    weight: 10
  - name: Topics
    url: https://jiaxun-li.github.io/blogs/en/tags/
    weight: 20
  - name: Academic 
    url: https://jiaxun-li.github.io
    weight: 30
