# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    pageRef: /blogs
    weight: 10
  - name: Topics
    pageRef: /tags
    weight: 20
  - name: Academic 
    url: https://jiaxun-li.github.io
    weight: 30
